WIP [一覧画面 API 接続]
CATechAccel/Colombia pull request #19
Opened 2021-02-17 02:56 UTC by Tech-Nayuta

## 関連するIssues
https://github.com/CATechAccel/Colombia/issues/18

## 変更内容

## 参考
- 

## その他 補足
-

2021-02-22 06:41 UTC, yamanetaisei approved these changes, later dismissed

2021-02-25 09:15 UTC, Tech-Nayuta commented
本日大幅修正いたしました！
21卒の方にレビューしていただきたいです！

2021-02-25 12:24 UTC, takumaosada reviewed
とりあえず

Colombia.xcodeproj/project.pbxprojの消去も

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/APIClient/APIClient.swift
> +                    return
ここの処理はもうちょいうまくできるはずなので考えて欲しい

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "per_page", value: "40"),
なんで40?(一般的なのは20)

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/Extension/ImageView+Ex.swift
> +}
これextensionにする意味あんまりないので業務なら却下される

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +    var isFavorite: Bool
命名としては`isFavorited`の方が良さそう

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +class FavoriteWorksIndexViewController: UIViewController {
finalつけれそう

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +    @IBOutlet weak var worksIndexCollectionView: UICollectionView! {
privateつけれそう

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            .subscribe(onNext: { [weak self] notification in
```suggestion
            .subscribe(onNext: { [weak self] work, actionAt in
```
みたいにする方が良さそう

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +                }
```suggestion
                let value = work.isFavorite ? favoriteWorks.value + [work] : favoriteWorks.value.filter({ $0.id != work.id })
                favoriteWorks.accept(value)
```

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        worksIndexCollectionView.collectionViewLayout = layout
didsetの中で良さそう

2021-02-25 12:24 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        let size = UIScreen.main.bounds.size
UIScreen使わなくてもできそう

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        return Int(ceil(Double(worksIndexModel.works.value.count) / 3))
returnいらない

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +class WorksIndexModel {
finalつけれそう

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +    static let shared = WorksIndexModel()
この後改行したい感

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexTabViewController.swift
> +        let vcList: [UIViewController] = [ worksIndexVC, favoriteWorksIndexVC ]
```suggestion
        let vcList: [UIViewController] = [worksIndexVC, favoriteWorksIndexVC]
```
このスペース開け方不自然かな

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +            .subscribe(onNext: { [weak self] notification in
同じく

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                    var works =  self.worksIndexModel.works.value as [Work]
asいらない

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                onNext: { [weak self] in
改行おかしそう

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        worksIndexCollectionView.collectionViewLayout = layout
didsetにかけそう

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +    @IBOutlet weak var worksIndexCollectionView: UICollectionView! {
private

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +    @IBOutlet weak var worksIndexCollectionView: UICollectionView! {
collectionViewは1vcに1つしかないので`collectionView`って名前にするのが一般的

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                    }
map使いましょう

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
>  class WorksIndexCollectionViewCell: UICollectionViewCell {
final

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        isHidden = false
これ必要？

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        guard let imageUrl = work.image.recommendedUrl, imageUrl != "" else {
`imageUrl != ""`は必要？

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        guard let imageUrl = work.image.recommendedUrl, imageUrl != "" else {
guard文使う感じじゃなさそう

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +    @IBOutlet weak var titleLabel: UILabel!
ここ以外にも他にもprivateつけれそうなのでつけましょう

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        }
ここでguard分使うべきではないかな

2021-02-25 12:24 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        return Int(ceil(Double(worksIndexModel.works.value.count) / 3))
returnいらない

2021-02-25 12:48 UTC, Tech-Nayuta commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "per_page", value: "40"),
シンプルに多くのデータをみたかったのと列数が3なので最後に2個余る場合と1個余る場合で表示に違和感がないか確認するためですかね！
一般的なのが20なのであれば20に変更しておきます！

2021-02-25 13:13 UTC, takumaosada commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "per_page", value: "40"),
一度に多くのデータを取得しようとすればするほどアプリのユーザー体験が悪くなるので画面いっぱいともう半分ぐらいが埋まる個数にするのが割と一般的(それが大体20なので20が一般的って言った)なので画面いっぱいともう半分ぐらいの個数をがいくつか計算してかつ３の倍数にするようにすれば良さそう

2021-02-25 13:19 UTC, Tech-Nayuta commented on Colombia/Sources/APIClient/APIClient.swift
> +                    return
了解です！
@yamanetaisei この部分たいせーのブランチでお願いできる？

2021-02-25 13:24 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        }
```Swift
       if index >= works.count  {
            DispatchQueue.main.async {
                cell.isHidden = true
            }
            return cell
        }
```
この場合は中身の処理(cellの操作)的にif文を使った方がいいという意味であってますか？

2021-02-25 13:27 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            .subscribe(onNext: { [weak self] notification in
その方がわかりやすかったですね！直します！

2021-02-25 13:41 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                    var works =  self.worksIndexModel.works.value as [Work]
valueがsetうけつけないので無理だと思ってたんですけど代入した時点で普通の配列になってたんですね...！
ありがとうございます！

2021-02-25 13:56 UTC, Tech-Nayuta commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        isHidden = false
CollectionViewのメソッドの中で isHidden = true を使用する部分があるのでこの記述がないと isHidden = trueのセルが差利用されてしまいます...！

2021-02-25 13:58 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        }
ちょっと違う
return cellは一回しか書くべきではないので

```
if index >= works.count  {
          DispatchQueue.main.async {
              cell.isHidden = true
          }
 }
else {

}
return cell
```
みたいな感じ

2021-02-25 13:58 UTC, takumaosada commented
後、それぞれのViewControllerの命名の仕方気になる

2021-02-25 13:59 UTC, Tech-Nayuta commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "per_page", value: "40"),
なるほどですね！
参考になります！ありがとうございます！😊

2021-02-25 14:00 UTC, ry-itto requested changes
ざーーっとみました 🙏🏼

2021-02-25 14:00 UTC, ry-itto commented on Colombia.xcodeproj/project.pbxproj
> +		04124976E20B30E0B9800C06 /* WorksIndexViewController.xib in Resources */ = {isa = PBXBuildFile; fileRef = 4E6D2DC44D41E3C29A1A9D60 /* WorksIndexViewController.xib */; };
xcodeproj 消そう

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "filter_season", value: "2020-spring")
`filter_season` が今仮の値ならここも仮の値だとコメントで示そう。
なんなら変更可能にするつもりなら TODO にしよう

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/Extension/ImageView+Ex.swift
> +//  ImageView+setImagebyNuke.swift
ファイル名が違う

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/Extension/UICollectionViewCell+Ex.swift
> +//  UICollectionViewCell + Nib + Identifer.swift
ditto

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +        self.isFavorite = false
サーバーからのレスポンスのパラメータとローカルで保存するパラメータが混在しているので、
必ずこうしろってわけじゃないけどやめておいた方がいいかな(可能なら お気に入り状態を保存するモデルとこれとは分けた方がいい）

サーバーからレスポンスきたタイミングでは全部お気に入りじゃないデータとして扱われるような形となるので

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +                cell.isFavorite = !cell.isFavorite
```suggestion
                cell.isFavorite.toggle()
```

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        // 詳細画面に移動
TODO にしよう

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        3
これは決めうちで大丈夫？
今はできなくて決めうちとかなら TODO つけよう

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        let index = indexPath.section * 3 + indexPath.row
何も考えてないんだけど、これはどうして？

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                work.isFavorite = !work.isFavorite
```suggestion
                work.isFavorite.toggle()
```

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexTabViewController.swift
>  class WorksIndexTabViewController: UITabBarController {
final つけれそうかな

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexTabViewController.swift
> -
ここは明けた方が自然かな

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +class WorksIndexViewController: UIViewController {
ditto

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +//一覧画面・お気に入り画面
このコメントあってる？

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                }
not を取るよりも equal を取る方がコードは読みやすいので、
`actionAt == .favorite` とかがよさそう

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                    }
Rx の map と Array の filter 使うといい感じになりそうだね

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                    self.worksIndexCollectionView?.reloadData()
どうして `?` で繋いでる？
繋ぐ必要はなさそうかな

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        present(alertController, animated: true, completion: nil)
completion 省略可能
```suggestion
        present(alertController, animated: true)
```

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +            retryhandler()
```suggestion
            retryHandler()
```

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        var work = works[index]
ここでは let で宣言して、変更したくなったタイミング（cell のボタンがタップされたタイミングで var に包み直してあげる方が良いかな

この work 変えたところで大元のデータが変わるわけでもないので勘違いが生まれる原因になりそう

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +}
命名が引数っぽいので、場所っぽい命名にした方が良いかな

2021-02-25 14:00 UTC, ry-itto commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        3
ここもきめうちで大丈夫？

2021-02-25 14:01 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        isHidden = false
ちなみにcell自体をhiddenにしたいのはなんで？

2021-02-25 14:14 UTC, takumaosada reviewed
追加で

2021-02-25 14:14 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                    <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" verticalCompressionResistanc
contentModeみたいな値はIBOutletのdidsetないでも記述した方が良さそう

2021-02-25 14:14 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="ONE PIECE" textAlignment="center" lineBreakMo
number of linesもそうしても良さそう

2021-02-25 14:14 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                        <fontDescription key="fontDescription" name="HelveticaNeue-Bold" family="Helvetica Neue" pointSize="10"/>
fontも変えるならそうするべきかな

2021-02-25 14:14 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.xib
> +        <deployment identifier="iOS"/>
この差分気になる

2021-02-25 14:14 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            cell.isFavorite = work.isFavorite
これmainThreadじゃないといけないものじゃなさそう

2021-02-25 14:15 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                    <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" verticalCompressionResistanc
ここら辺の線引きは曖昧だけど基本的にはcontraint以外の値ほとんどはコードでdidset内にも(にだけ)書いてあげる方が自分以外の実装者に優しいコードになる

2021-02-26 07:34 UTC, Tech-Nayuta commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        guard let imageUrl = work.image.recommendedUrl, imageUrl != "" else {
動作確認しましたが必要なさそうでした。imageUrl = work.image.recommendedUrlで空文字も排除してくれるんですね！

2021-02-26 07:38 UTC, Tech-Nayuta commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        guard let imageUrl = work.image.recommendedUrl, imageUrl != "" else {
確かに、フィルターかかってreturnされるのちょっと違いますね

2021-02-26 07:43 UTC, Tech-Nayuta commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "filter_season", value: "2020-spring")
@yamanetaisei

2021-02-26 07:44 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        guard let imageUrl = work.image.recommendedUrl, imageUrl != "" else {
そういうことではないよ
ちなみに確認だけどこの空文字除去の処理はapiのレスポンスとして空文字が帰ってくるからやったって感じ？
そうならやるべき場所はdecodeするタイミングとかなのでここでやるのは違う気がする

2021-02-26 07:49 UTC, Tech-Nayuta commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        guard let imageUrl = work.image.recommendedUrl, imageUrl != "" else {
そうですね、一部データにOptional("")があったので空文字も排除しました。
 了解です！
@yamanetaisei

2021-02-26 08:43 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        3
あまりよくないと思ったので

```Swift
//  UICollectionView+Ex.swift

import UIKit

extension UICollectionView {
    var rowNum: Int {
        get {
            return 3
        }
    }
}
```
という形でUICollectionViewの拡張ファイルの中で定義したのですがやり方的にあってますか？

2021-02-26 08:46 UTC, Tech-Nayuta commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +        self.isFavorite = false
```
サーバーからレスポンスきたタイミングでは全部お気に入りじゃないデータとして扱われるような形となるので
```
ここは元々そのつもりでした！

処理の流れとして
1. APIClientから取得時点では全てisFavoritedはfalse
2. Realmでお気に入り登録している作品データがそのなかにあればそのデータのisFavoriteをtrueにする
みたいな流れにしようと思っていました！

2021-02-26 08:47 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +                cell.isFavorite = !cell.isFavorite
そんな便利なプロパティが...！勉強になります🙇‍♂️

2021-02-26 08:51 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +//一覧画面・お気に入り画面
間違っているので直しました

2021-02-26 08:53 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                }
これは今後拡張性かんがえてさらに画面が増えたときにその画面からのお気に入りの変更も反映できるようにしようとおもって!= の形にしたのですが考えすぎでしたか？笑

2021-02-26 09:00 UTC, takumaosada commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +        self.isFavorite = false
それだと最初は全部falseになるのでそうではなく、initする段階で制御するべきなので、りょうちゃんの言ったようにdecodeするためのモデルとは別のモデルを定義した方がいいと思う

2021-02-26 09:04 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                }
拡張する事を考えてるならなおさらでみたいにするべき
```
if actionAt == .favorite || actionAt == .hoge {
```

2021-02-26 09:18 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        3
てかこれ３個のセルの集合体を1セクションにしてるけどそうしてること自体が間違ってそう
今回の場合はsectionの数は一個になるはずで、`numberOfItemsInSection`はworksの合計値と同じになるべきだと思う

2021-02-26 09:22 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                }
たしかにその方が可読性が高いですね！笑
ご意見ありがとうございます🙇‍♂️

2021-02-26 13:09 UTC, yamanetaisei commented on Colombia/Sources/APIClient/APIClient.swift
> +                    return
りょ

2021-02-26 14:05 UTC, ry-itto commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +        self.isFavorite = false
おさたくの言ってることが言いたかったこと

単純にやってほしいことを言うと ここには `isFavorited` は入れないでほしい

2021-02-26 14:06 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        3
ごめんリアクションだと大丈夫なのかどうかがわからないかな

2021-02-26 14:07 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                }
可読性とかを考えると、 OR を取るのももちろんあるんだけど、
Swift は `switch-case` が強力なので、そっちで書く方が読みやすいかな

2021-02-26 14:08 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        3
たしかに！セクション数定義する意味なかったですね笑
なおします！

2021-02-26 14:08 UTC, ry-itto commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        3
あまり良くない、というよりはおさたくの言ってる通り、そもそも3で固定するのが間違えていそうなんよね

どちらかというと意図を聞きたい感はある

2021-02-26 14:11 UTC, ry-itto commented on Colombia/Sources/APIClient/APIClient.swift
> +                    return
ちょっと良くわかってないんだけど、元々たいせいがやってたブランチから修正したって感じ？

PRの単位としてはなゆたの PR なので、特段理由がなければなゆたが直すべきではある

2021-02-26 14:11 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        3
すみませんリアクションは完了しました大丈夫ですっていうサインです！笑

2021-02-26 14:12 UTC, ry-itto commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "per_page", value: "21"),
!?

2021-02-26 14:12 UTC, ry-itto commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "per_page", value: "21"),
20 で良くない？w

2021-02-26 14:18 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        let index = indexPath.section * 3 + indexPath.row
cellのindexPathが [section, row]の2次元配列に対して表示させる作品群worksは一次元配列だったのでそれに対応させるように計算させていました！
ただsectionは今回複数用意する必要ない事に気づいて1個に変更したのでこの部分の処理は

let index = indexPath.rowという形に書き換えています！

2021-02-26 14:21 UTC, ry-itto requested changes
少し追加 🙏🏼

2021-02-26 14:21 UTC, ry-itto commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +//            let cellSize = (collectionView.bounds.width - 30) / 3.5
不要そうなコメントは消そう

2021-02-26 14:21 UTC, ry-itto commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +
改行は一個でよさそう

2021-02-26 14:21 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +}
型定義の時には省略形の命名はしない方がいいかな
`ViewController` ってなるのは微妙だけど

2021-02-26 14:21 UTC, ry-itto commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        if let image = work.image.recommendedUrl, let imageUrl = URL(string: image) {
`work.image.recommendedUrl` で取れるのは image の URL の String なのでそれに合った命名にしよう

2021-02-26 14:24 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                }
なるほど！
```Swift
    switch actionAt {
      case .favorite, .pattern3:
          print()
      default:
          print()
      }
```
これで書くイメージですよね！

2021-02-26 14:26 UTC, ry-itto commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                }
`default` は書かない方がいいですー

あくまで `switch-case` で `case` が網羅されていればそれに関する考慮がなされていて、
もし新しい case が増えたとしてもコンパイルエラーで気づけるので どうしても何かしら理由がない限りは `default` は書かない感じが良いです

2021-02-26 14:27 UTC, Tech-Nayuta commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                    <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" verticalCompressionResistanc
そうなんですね！
実務ではxibファイルで確認するよりコンポーネントのdidSetの中身で確認することの方がおおいんですか？

2021-02-26 14:33 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                    <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" verticalCompressionResistanc
xibファイルは可読性が皆無なので大抵の人はreview時にスルーしてしまうので十分な情報量がないままreviewするので以下のことをやってなるべく補う
- PRにスクショを掲載する(動画でも可)
- ちょっと特殊なものを指定してる時はdidset内で定義することでコードとして可視化できる

上にも書いたけどcontraitの値とかはかスクショで保管して、特殊なパラメーターの指定(numberoflinesとか背景色とかフォントとか)はコードで行うのが割と一般的だと思う

2021-02-26 14:37 UTC, Tech-Nayuta commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                    <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" verticalCompressionResistanc
あああ！たしかにコードレビューするときxibファイルあんま確認しないですね！笑
なるほどですね！！

2021-02-26 14:38 UTC, yamanetaisei commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "per_page", value: "21"),
コレクションビューが3行だから、３の倍数にしたのです。
<img src="https://user-images.githubusercontent.com/50735539/109313360-785bc700-788b-11eb-8992-533764bae693.png" width="100px">

2021-02-26 14:38 UTC, takumaosada commented
@Tech-Nayuta Colombia.xcodeproj/project.pbxprojの不要な差分出てるので最新のmainブランチpullしてきてもいいかも

2021-02-26 14:47 UTC, Tech-Nayuta commented on Colombia/Sources/View/WorksIndexCollectionViewCell.xib
> +                    <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" verticalCompressionResistanc
PRの参考のところにも載せてますが動画(GIF)をアップロードしたのでご覧ください！

**DEMO動画**
APIのフェッチ（リフレッシュ）とお気に入り登録してからお気に入り画面にそのアイコンが表示される
　https://gyazo.com/f049693db8ec63c5fddc74f29d972dce
一覧画面でお気に入り解除してからお気に入り画面にそのアイコンが消えていることの確認
https://gyazo.com/81670c33f10c4670c19b6f6de238cb62
お気に入り画面でお気に入り解除されてから一覧画面に戻るとそのアイコンのハートマークが灰色に（お気に入り解除）
https://gyazo.com/ffee40eb1d14a7a4cc8677e0a51f302a

2021-02-26 14:49 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.xib
> +        <deployment identifier="iOS"/>
この差分なんのやつなんでしょう...ちょっと調べてみます

2021-02-26 14:51 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +}
なるほどですね...！
ちなみにりょうちゃんだったらどのように命名しますか...？

2021-02-26 14:53 UTC, yamanetaisei commented on Colombia/Sources/APIClient/APIClient.swift
> +                    return
もともとなゆたが、僕に対して修正リクエストをしてくれたんですけど、僕がPRを出して修正する前に、なゆたが、このPR上で、自分で修正して、pushしちゃったみたいです。なので、本来はこの差分はこのPRにのせずに、僕が修正する予定だったわけです。
[参考](https://github.com/CATechAccel/Colombia/pull/27)

2021-02-26 15:13 UTC, yamanetaisei commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +}
( ^ω^ )ノ==[codic](https://codic.jp/)
　　ﾎﾟｰｲ

2021-02-26 17:20 UTC, ry-itto commented on Colombia/Resources/Info.plist
> +		</dict>
これはどうして追加している感じ？

いらない気がしてる。。

2021-02-27 00:47 UTC, Tech-Nayuta commented on Colombia/Resources/Info.plist
> +		</dict>
あ、これもういらないです
消し忘れてました....ありがとうございます！

2021-02-27 00:50 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +}
あざす！参考にする！

2021-02-27 00:54 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        3
これは表示する時のアイコンの列数を3にしたかったのでセクション内のセルを3に固定していました。
結局その部分は表示にあまり関係がなかったのですが....笑

2021-02-27 01:02 UTC, Tech-Nayuta commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +        self.isFavorite = false
りょうかいです！修正します👍

2021-02-27 05:22 UTC, takumaosada reviewed
コメントが増えてる気がするんだけど自明なコメントとか実装者が頭整理するためのコメントはmergeする前に消去した方が良さそう

自明なコメントはむしろ可読性を下げてしまうし、コメントも他のコードと同じで管理コストがあったりする。(例えばコメントの書いてるコードの部分を修正したけどコメントの内容は修正しなかったらコメントは嘘を書いてることになる)

逆にコメントはコードを読んでも他の人が理解しにくいもの(uikitのバグを踏まないためのworkaroundをやってる箇所とか)を書くべき。

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/Extension/UICollectionView+Ex.swift
> +}
extensionとして生やすべきではなさそう

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +    //Decode用
不要なコメントは消去したい

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/Repository/AnnictDataRepository.swift
> -
このファイル差分全体的に修正する必要性ないかも

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +//お気に入り画面
こういうのはViewControllerの名前がその役割のはずなので消去したい

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            let cellSize = 240 / collectionView.showingRowNum
240固定にしてると他の端末サイズだと崩れると思う

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            layout.itemSize = CGSize(width: cellSize, height: cellSize + 15)
この15は何してるの？(やり方間違ってるかも)

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        //お気に入りの状態に変更があった時
initにここら辺の処置書いちゃよくない(viewDidLoadに書くべき)

2021-02-27 05:22 UTC, ostk0069 commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +
この改行いらない

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        collectionView.backgroundView = bgImage
これもdidsetないに書くで良さそう

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        }
修正されてなさそう

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        guard index < works.count else {
なんでこの処理必要なの？

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +                cell.isHidden = true
隠すのではなくてcell自体を消去して欲しい

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            .asDriver()
tap処理の時点でmainThreadで実行されてるのでdriverにする必要ない

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +enum CallingViewController {
この命名よくなさそう

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +        return favoriteWorks.value.contains{ $0.id == workId }
```suggestion
        favoriteWorks.value.contains { $0.id == workId }
```

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +            let cellSize = 240 / collectionView.showingRowNum
ditto

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +        collectionView.backgroundView = bgImage
ditto

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +//一覧画面
ditto

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        else{
```suggestion
        else {
```

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
>      @IBOutlet weak var favoriteButton: UIButton!
```suggestion
    @IBOutlet private(set) weak var favoriteButton: UIButton!
```

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                .asDriver()
ditto

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +            .subscribe(onNext: {[weak self] work, callingVC in
subscribeとonNextの間で改行する時としない時があるのどっちかに揃えて欲しい (チーム間での統一も含めて)

2021-02-27 05:22 UTC, takumaosada commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +                        )
改行の仕方がおかしそう(idの直前で改行する方が良さそう)

2021-02-27 05:33 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            layout.itemSize = CGSize(width: cellSize, height: cellSize + 15)
セルのLabel部分の高さです。その場しのぎ感で書いたので間違ってる感じしかしないんですが笑

![スクリーンショット 0003-02-27 14 32 45](https://user-images.githubusercontent.com/59905087/109376562-a9c6a800-7908-11eb-9607-8a2563bd4cf9.png)

2021-02-27 05:36 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            layout.itemSize = CGSize(width: cellSize, height: cellSize + 15)
修正頼んだ笑

2021-02-27 05:55 UTC, yamanetaisei commented
@Tech-Nayuta 
このPRをｻﾞｰッとおったけど、自分が修正する箇所は。
- APIClientのerrorの処理
- Optional("")の除去
- URLQueryItemのTODOコメント
↑であってる？こぼしてたらごめん

2021-02-27 05:56 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            let cellSize = 240 / collectionView.showingRowNum
UIScreenの変わりをどうするか考えていていまかわりに240で設定してます。 なおしておきます

2021-02-27 05:56 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        //お気に入りの状態に変更があった時
worksIndexModelをDIっぽく書いている部分ですか？
それともRxの購読の記述ですか？
（Rxの購読の記述はviewDidLoadに書くとAPIで取得したときにsubscribeされなくなります...）

2021-02-27 06:01 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        //お気に入りの状態に変更があった時
Rxの購読の記述の記述の方。
ちゃんと見てないけどそれはviewDidLoadに書いてることが問題ではなく別の問題が起きてると思う

2021-02-27 06:02 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        //お気に入りの状態に変更があった時
worksIndexModelをDIっぽく書いている部分はそのままでよき。

2021-02-27 06:11 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        //お気に入りの状態に変更があった時
なるほどですね！
ちなみにinitではなくviewDidLoadに書かせるのはtabBarController開いた時点で別の画面のRx部分の処理(今回のinitでRxの記述をしている部分)を呼び出させないためという認識であってますよね！

2021-02-27 06:14 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        //お気に入りの状態に変更があった時
> tabBarController開いた時点で別の画面のRx部分の処理(今回のinitでRxの記述をしている部分)を呼び出させないため

これの意味があんまりよくわかってないのでどっちかわからないけど、initのタイミングだとそのVCにあるcustom view, collectionView, buttonみたいのがちゃんと定義されてない可能性があるのでクラッシュする可能性とか不都合が起きる可能性があるから

2021-02-27 06:17 UTC, Tech-Nayuta commented
あってるよ！

2021-02-27 06:22 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        //お気に入りの状態に変更があった時
一覧画面を開いたときにお気に入り画面のinit()が呼び出されるのでタイミング的にそこではなくお気に入り画面へ移動したとき（つまりViewDidLoadが呼び出されるタイミング）の方がいいのかな？と思っていました。

あ、確かにinitで書くとクラッシュしますね笑  これからviewDidLoadに書くようにします笑

2021-02-27 06:31 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +        guard index < works.count else {
これ1セクションあたりの要素数3で設定していたときにいらない要素に対して非表示にする目的で作ってたやつです。
もういらないですね笑

2021-02-27 06:32 UTC, takumaosada commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            let cellSize = 240 / collectionView.showingRowNum
collectionView.bouds.width使うののがいいと思う(元々使ってたのに固定にしたからなんでなのかずっと思ってた)

2021-02-27 07:02 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            .asDriver()
あ、そうなんですね！了解です！

2021-02-27 07:10 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexViewController.swift
> +            .subscribe(onNext: {[weak self] work, callingVC in
たしかにぶれてますね、了解です

2021-02-27 07:14 UTC, Tech-Nayuta commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +    //Decode用
@yamanetaisei

2021-02-27 07:23 UTC, yamanetaisei commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +    //Decode用
この差分に関しては、このPRでなゆたが追加したやつだと思うから、なゆたが消しちゃってもいいと思ってるけどどう？
@Tech-Nayuta

2021-02-27 07:24 UTC, Tech-Nayuta commented on Colombia/Sources/Model/AnnictAPIModel.swift
> +    //Decode用
あ、了解した！

2021-02-27 08:20 UTC, yamanetaisei commented on Colombia/Sources/View/WorksIndexCollectionViewCell.swift
> +        guard let imageUrl = work.image.recommendedUrl, imageUrl != "" else {
これ思ったんだけど、`recommennded_url`がnilじゃなくて、`""`で帰ってくるなら、modelの`recommendedUrl`をoptionalで定義するのをやめて、`isEmpty`でから文字をチェックすればいいんじゃない？
@Tech-Nayuta 

。。。検討ハズレなこと言ってたらごめん

2021-02-27 08:40 UTC, yamanetaisei commented on Colombia/Sources/APIClient/AnnictAPIRequest.swift
> +                URLQueryItem(name: "filter_season", value: "2020-spring")
`filter_season`に関しても、なゆたが追加したやつだから、なゆたがコメントを入れればいいと思う。
そもそも、このPRの差分だから、mergeされない限り、自分のローカルには、`filter_season`が反映されないよ。

2021-02-27 11:51 UTC, Tech-Nayuta commented
まだレビューで修正できていない部分があるんですけど
たいせーとアントニーが作業できるようにいったんこのプルリクをマージします。
残りの修正は別のissueとブランチ立てて作業します！

2021-02-27 12:01 UTC, yamanetaisei approved these changes
とりあえずOK

2021-02-27 12:05 UTC, Yoshitsugu-Antony-Kambara approved these changes
新しくIssue立てる旨承知した
めちゃくちゃ助かります🙇‍♂️

2021-02-27 12:05 UTC, Yoshitsugu-Antony-Kambara commented on Colombia/Sources/View/Home/WorksIndexTabViewController.swift
> +}
これって、まだ最終的にAPIからどのデータを取得するか決まってないから後々消去するっていうコメントしてるの？

2021-02-27 13:56 UTC, ry-itto reviewed
このブランチから新しく切って、このブランチを対象にPR作ればいい気もするけど。。

2021-02-27 14:03 UTC, ry-itto approved these changes

2021-02-27 14:11 UTC, Tech-Nayuta commented
あああ確かにそうしてもよかったですね笑
ただちょっと今回はもうマージする形にします。🙇‍♂️

2021-02-27 14:11 UTC, merged

2021-03-04 06:01 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            layout.itemSize = CGSize(width: cellSize, height: cellSize + 15)
すみません、修正するとはいいつつここをどういう風に表現していいのかわからないので
```Swift
            let titleLabelSize = CGFloat(15)
            layout.itemSize = CGSize(width: cellSize, height: cellSize + titleLabelSize)
```
て書いたのですがもっといい方法はないですか...？
UICollectionViewCellのインスタンスを取り出してそこからcell.titleLabel.bounds.heightとかいて呼び出すしかないですか...？

2021-03-04 06:07 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/FavoriteWorksIndexViewController.swift
> +            layout.itemSize = CGSize(width: cellSize, height: cellSize + 15)
すみません、修正するとはいいつつここをどういう風に表現していいのかわからないので
```Swift
            let titleLabelSize = CGFloat(15)
            layout.itemSize = CGSize(width: cellSize, height: cellSize + titleLabelSize)
```
て書いたのですがもっといい方法はないですか...？
UICollectionViewCellのインスタンスを取り出してそこからcell.titleLabel.bounds.heightとかいて呼び出すしかないですか...？

2021-03-04 06:08 UTC, Tech-Nayuta commented on Colombia/Sources/View/Home/WorksIndexModel.swift
> +enum CallingViewController {
CallingViewControllerTypeに変更します！