XcodeGen用のproject.ymlの設定
CATechAccel/Colombia pull request #21
Opened 2021-02-20 04:33 UTC by Tech-Nayuta

## 関連するIssues

## 変更内容
XcodeGenを生成してProjectファイルのコンフリクトを防止する。

## 参考
- 

## その他 補足
-

2021-02-20 13:01 UTC, ry-itto requested changes

2021-02-20 13:01 UTC, ry-itto commented on project.yml
> +      - target: Colombia
UITest のターゲット足りないかな

2021-02-20 13:01 UTC, ry-itto commented on project.yml
> +      - target: Colombia
`project.yml` 作るなら `*.xcodeproj` 消しちゃおう

2021-02-22 01:10 UTC, Tech-Nayuta commented
修正しました！確認おねがいします！
GithubActionでxcodegen対応できるようにお願いしていただいてもよろしいですか！

2021-02-22 02:46 UTC, ry-itto commented
そんなに難しくないので自分でやってみて〜

2021-02-22 03:01 UTC, Tech-Nayuta commented
了解です！

2021-02-22 04:24 UTC, takumaosada commented on project.yml
> +      - target: Colombia
xcworkspaceもじゃないかな

2021-02-22 08:14 UTC, Tech-Nayuta commented
xcodegenのCIへの導入ができました！確認おねがいします！

2021-02-22 08:15 UTC, Tech-Nayuta commented on project.yml
> +      - target: Colombia
現時点でxcodeprojしか生成できないのですがxcworkspaceも生成できるようにした方がいいですか？

2021-02-22 08:28 UTC, ry-itto commented on project.yml
> +      - target: Colombia
精製してると思うよー

2021-02-22 08:34 UTC, Tech-Nayuta commented on project.yml
> +      - target: Colombia
![スクリーンショット 0003-02-22 17 31 59](https://user-images.githubusercontent.com/59905087/108682722-02c2c480-7534-11eb-8e2b-03d862e45a4f.png)

この画像みた感じxcodeprojだけしか作られてないっぽいんですがこれでも生成できてますか、、？

2021-02-22 08:36 UTC, ry-itto commented on project.yml
> +      - target: Colombia
それは正しくて

pod install

したら生成されるので問題ないってのと、もし生成できてなかったらビルド失敗するかな

2021-02-22 08:39 UTC, Tech-Nayuta commented on project.yml
> +      - target: Colombia
あ、workspaceインストールするタイミングは確かにpod installでしたね！
理解しました！

2021-02-22 08:42 UTC, Tech-Nayuta commented
xcworkspace消しておきました！

2021-02-22 09:37 UTC, takumaosada commented on project.yml
> +      - target: Colombia
https://github.com/CA21engineer/cta_reactive_master_answer/blob/main/Makefile みたいにmakefileにコマンド追加してそれ使うようにすると忘れないかもね

2021-02-22 11:55 UTC, Tech-Nayuta commented on project.yml
> +      - target: Colombia
たしかに...!!  参考にします！
makeコマンド再帰的に使うこともできるんですね！

2021-02-22 13:20 UTC, yamanetaisei approved these changes

2021-02-22 15:43 UTC, ry-itto approved these changes
LGTM

2021-02-22 15:44 UTC, Tech-Nayuta commented
Mergeします！！

2021-02-22 15:45 UTC, merged